### ISSUE TITLE
CUDA driver version is insufficient

### ISSUE THREAD

**Issue by sungwonida** [phvu/cuda-smi#10]
I got an error saying, `Error: CUDA driver version is insufficient for CUDA runtime version in cudaGetDeviceCount at ./cuda-smi.cpp:23`.  
I use CUDA 9.2 with driver 396.148 under macOS 10.13.6.  
Please have this issue taken a look.  
Thanks in advance.

**Comment by MaffooBristol** [comment]
Same here with Cuda driver `410.130` on a 2012 Macbook Pro, OSX 10.12.6

**Comment by sungwonida** [comment]
Actually, the issue has been solved for me. Please refer to this link.  
https://discuss.pytorch.org/t/error-in-cuda-driver-while-running-a-pytorch-code/24221/12?u=ki2rin
